meta_product_name: "Jaunt"
meta_title: "Jaunt - Explore more"
meta_description: "Travel on a budget with suggestions from travellers, easily place your chosen activities in a plan for your time"
meta_image: "mountains.jpg" # should exist in `app/assets/images/`
